import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import Providers from '@/providers/Provider';
import { Toaster } from 'sonner';

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Exclusive - All in one site',
  description: 'Generated by create next app',
  authors: [
    { name: 'Md. Rezaul Karim', url: 'https://mdrezaulkarim.vercel.app/' },
  ],
  creator: 'Md. Rezaul Karim',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Providers>
          <Toaster richColors position="top-center" />
          {children}
        </Providers>{' '}
      </body>
    </html>
  );
}
